-- Run once in Supabase SQL Editor.
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  fingerprint text not null check (char_length(fingerprint) between 1 and 64),
  page_path text not null default '/' check (char_length(page_path) between 1 and 512),
  created_at timestamptz not null default now()
);

create index if not exists visits_fingerprint_idx on public.visits (fingerprint);
alter table public.visits enable row level security;

drop policy if exists allow_public_insert on public.visits;
create policy allow_public_insert
  on public.visits for insert to anon, authenticated
  with check (true);

-- Raw fingerprints and paths must never be readable by public clients.
revoke all on table public.visits from anon, authenticated;
grant insert on table public.visits to anon, authenticated;

create or replace function public.get_site_stats()
returns table (uv bigint, pv bigint)
language sql
security definer
set search_path = public
stable
as $$
  select count(distinct fingerprint)::bigint, count(*)::bigint
  from public.visits;
$$;

revoke all on function public.get_site_stats() from public;
grant execute on function public.get_site_stats() to anon, authenticated;
